CONFIG_ANT=y
# Evaluation key for ANT
# Set this Kconfig to use the evaluation stack for DUAL CORE builds (for example, nRF53 Series).
# You MUST obtain a valid commercial license key BEFORE releasing a product to market that uses ANT.
# For more information about licensing please see CONFIG_ANT_LICENSE_KEY and visit the website below:
# https://www.thisisant.com/developer/ant/licensing
CONFIG_ANT_EVALUATION_KEY=y  # was n

CONFIG_ANT_NP=y
CONFIG_ANT_RPC=y

CONFIG_NRF_RPC=y
CONFIG_NRF_RPC_THREAD_STACK_SIZE=4096
CONFIG_THREAD_CUSTOM_DATA=y
CONFIG_NRF_RPC_LOG_LEVEL_DBG=n
CONFIG_NRF_RPC_TR_LOG_LEVEL_DBG=n
CONFIG_NRF_RPC_OS_LOG_LEVEL_DBG=n

CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y

CONFIG_DEBUG_OPTIMIZATIONS=n
CONFIG_DEBUG=n

CONFIG_HEAP_MEM_POOL_SIZE=4096


# Enable LED and button library
CONFIG_DK_LIBRARY=y

# Enable USB device stack
CONFIG_USB=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_DRIVER=y
CONFIG_USB_DEVICE_PRODUCT="ANT+ USB Stick"
CONFIG_USB_DEVICE_MANUFACTURER="CC 2024"
CONFIG_USB_DEVICE_VID=0x0FCF  # Example
CONFIG_USB_DEVICE_PID=0x1008  # Example
CONFIG_USB_DEVICE_SN="123456789"  # Example

# If needed, enable a USB class, for instance CDC ACM if you want a serial port:
# CONFIG_USB_CDC_ACM=y