#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0

"""Stall the host's bulk-IN reads and prove the dongle survives it.

This is the verification for the bounded bulk-IN wait in
apps/common/usb_ant_class.c. The bug it covers cannot be reached from a unit
test, on the target or off it: it needs a real USB host that stays CONFIGURED
and simply stops polling IN. A device that is suspended, reset or unplugged
takes a different path entirely (the status callback tears the transfers down),
and those are the only stalls a test harness can fake. So the test is this
script, against real hardware, and the counters in the 0xF6 reply are how its
result is read.

What used to happen: usb_ant_write() held tx_mutex across a usb_transfer_sync()
that waited K_FOREVER. One unread bulk-IN transfer parked the bridge thread
permanently, with the mutex held, so the USB TX thread queued behind it and the
dongle answered nothing ever again - short of a replug.

    # Feather DUT (legacy USB + health.conf), an ANT+ master transmitting
    python tools/bench_usb_stall.py
    python tools/bench_usb_stall.py --json stall-legacy.json

The shape of the run:

  1. read the 0xF6 counters (baseline)
  2. open a wildcard ANT+ slave channel, so the DONGLE is producing traffic of
     its own for the whole run - this is the load, and without a master on the
     air there is nothing to stall and the script refuses to report a pass
  3. read normally for 5 s
  4. STOP READING for 15 s while the dongle keeps producing. No suspend, no
     reset: the device stays configured and the host just never submits an IN
     transfer. This is the exact condition
  5. resume, and time how long a `request capabilities` takes to come back
  6. read the counters again

Pass requires all three: the request round-trips in under 2 s, `tx_timeout` has
climbed (the firmware detected the stall and abandoned the wait), and
`tx_drops` has climbed (events really were produced with nowhere to go, so the
stall was real and not an artefact of an idle radio).

Needs CONFIG_ANT_DONGLE_HEALTH_COUNTERS=y - two of the three assertions are
counter reads. Build with `-DEXTRA_CONF_FILE=health.conf`.

WHY THE TRAFFIC REQUIREMENT IS LOAD-BEARING, AND NOT MERELY TIDY. Measured
2026-08-16, and it cost a false pass to learn. Simply not calling read() does
NOT stop the host from draining bulk-IN: libusb-win32 keeps its own buffer, so
a trickle of small replies - request/response traffic generated by the script
itself, with no radio involved - is absorbed by the host and the endpoint never
backs up. A reduced variant of this test built on that trickle reported PASS
against a fixed image AND against firmware that predates the fix entirely, i.e.
it was measuring nothing.

Real radio traffic at a channel period is what actually fills the endpoint
faster than the host retires it, which is the only thing that produces the
condition. So `--negative-control` is not optional politeness: run it against a
pre-fix image before believing any pass, because a stall that does not
reproduce makes a pass on the fixed image worthless. The refusal above when
`before_packets == 0` is the same guard in automatic form - do not route around
it.
"""

from __future__ import annotations

import argparse
import json
import sys
import time

try:
    import usb.core  # noqa: F401 - import-guard, verifies pyusb is installed
except ImportError:  # pragma: no cover - user-facing guidance
    sys.exit("pyusb is not installed. Run: pip install pyusb")

sys.path.insert(0, __file__.rsplit("\\", 1)[0].rsplit("/", 1)[0])

# The 0xF6 request and its version-aware decode are ant_health.py's, not a
# second copy here. That module owns the field table and the rule for reading a
# v1 body off an older stick; duplicating either is how two tools end up
# disagreeing about what a counter means.
from ant_health import decode as decode_health  # noqa: E402
from ant_health import request as request_health  # noqa: E402
from ant_probe import (  # noqa: E402
    EP_OUT,
    FrameReader,
    close_device,
    frame,
    open_device,
    reset_stack,
)
from ant_wire import (  # noqa: E402
    MESG_ACKNOWLEDGED_DATA_ID,
    MESG_ASSIGN_CHANNEL_ID,
    MESG_BROADCAST_DATA_ID,
    MESG_BURST_DATA_ID,
    MESG_CAPABILITIES_ID,
    MESG_CHANNEL_ID_ID,
    MESG_CHANNEL_MESG_PERIOD_ID,
    MESG_CHANNEL_RADIO_FREQ_ID,
    MESG_CHANNEL_SEARCH_TIMEOUT_ID,
    MESG_CLOSE_CHANNEL_ID,
    MESG_NETWORK_KEY_ID,
    MESG_OPEN_CHANNEL_ID,
    MESG_REQUEST_ID,
    MESG_RESPONSE_EVENT_ID,
)

# Same public ANT+ key, frequency and wildcard slave setup as tools/ant_scan.py
# - see that file for what each step is for.
ANT_PLUS_KEY = bytes([0xB9, 0xA5, 0x21, 0xFB, 0xBD, 0x72, 0xC3, 0x45])
ANT_PLUS_FREQ = 57
CHANNEL = 0

DATA_IDS = (MESG_BROADCAST_DATA_ID, MESG_ACKNOWLEDGED_DATA_ID,
            MESG_BURST_DATA_ID)

CAPABILITIES_REQUEST = frame(MESG_REQUEST_ID,
                             bytes([0x00, MESG_CAPABILITIES_ID]))


def command(dev, reader, msg_id: int, payload: bytes, name: str,
            timeout: float = 2.0) -> bool:
    """Send a configuration message and wait for its 0x40 acknowledgement."""
    dev.write(EP_OUT, frame(msg_id, payload))

    deadline = time.monotonic() + timeout
    while True:
        result = reader.next_frame(deadline)
        if result is None:
            print(f"  FAIL: {name} was not acknowledged")
            return False

        got_id, body = result
        if got_id == MESG_RESPONSE_EVENT_ID and len(body) >= 3:
            if body[1] != msg_id:
                continue
            if body[2] != 0:
                print(f"  FAIL: {name} rejected, code {body[2]}")
                return False
            print(f"  OK: {name}")
            return True


def open_channel(dev, reader) -> bool:
    steps = [
        (MESG_NETWORK_KEY_ID, bytes([0]) + ANT_PLUS_KEY, "network key"),
        (MESG_ASSIGN_CHANNEL_ID, bytes([CHANNEL, 0x00, 0x00]),
         "assign channel (slave)"),
        (MESG_CHANNEL_ID_ID, bytes([CHANNEL, 0, 0, 0, 0]),
         "wildcard channel id"),
        (MESG_CHANNEL_RADIO_FREQ_ID, bytes([CHANNEL, ANT_PLUS_FREQ]),
         "radio frequency 2457 MHz"),
        (MESG_CHANNEL_MESG_PERIOD_ID, bytes([CHANNEL, 0x86, 0x1F]),
         "message period"),
        (MESG_CHANNEL_SEARCH_TIMEOUT_ID, bytes([CHANNEL, 0xFF]),
         "infinite search timeout"),
        (MESG_OPEN_CHANNEL_ID, bytes([CHANNEL]), "open channel"),
    ]
    # all() over a generator short-circuits, so a refused step stops the
    # sequence rather than issuing the rest against a channel that never got
    # configured - command() has already printed which one it was.
    return all(command(dev, reader, msg_id, payload, name)
               for msg_id, payload, name in steps)


def read_for(reader, seconds: float) -> int:
    """Read frames for `seconds`, returning how many carried ANT data."""
    packets = 0
    deadline = time.monotonic() + seconds
    while time.monotonic() < deadline:
        result = reader.next_frame(min(deadline, time.monotonic() + 0.5))
        if result is None:
            continue
        if result[0] in DATA_IDS:
            packets += 1
    return packets


def await_capabilities(reader, timeout_s: float) -> float | None:
    """Time a capabilities reply. Returns seconds, or None if it never came.

    Anything queued from before the stall is read on the way past and counts
    against the elapsed time on purpose: "the dongle answers again" means the
    answer reached the host, backlog and all.
    """
    start = time.perf_counter()
    deadline = start + timeout_s
    while True:
        result = reader.next_frame(deadline)
        if result is None:
            return None
        if result[0] == MESG_CAPABILITIES_ID:
            return time.perf_counter() - start


def read_health(dev, reader, label: str) -> dict | None:
    body = request_health(dev, reader)
    if body is None:
        return None
    try:
        got = decode_health(body)
    except ValueError as exc:
        print(f"  malformed 0xF6 reply ({label}): {exc}")
        return None
    return got


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--read-seconds", type=float, default=5.0,
                        help="normal reading before the stall (default: 5)")
    parser.add_argument("--stall-seconds", type=float, default=15.0,
                        help="how long to stop reading bulk-IN for. Must be "
                             "comfortably longer than the firmware's 1 s "
                             "per-transfer timeout, so that several transfers "
                             "time out and not just one (default: 15)")
    parser.add_argument("--resume-timeout", type=float, default=2.0,
                        help="how long a request may take after the stall "
                             "before this is a failure (default: 2)")
    parser.add_argument("--after-seconds", type=float, default=5.0,
                        help="reading after the stall, to show the event flow "
                             "came back and not just the command path "
                             "(default: 5)")
    parser.add_argument(
        "--negative-control", action="store_true",
        help="invert the verdict: expect the assertions to FAIL. Run this "
             "against a build WITHOUT the bounded wait (the pre-W6 legacy "
             "image) - if the script passes there, it is not stalling "
             "anything and a pass on the fixed image proves nothing. Run the "
             "plain command on the USB_NEXT build too (next.conf;health.conf) "
             "as the cross-stack control: that stack has had a bounded wait "
             "since W1, so it must pass identically, and a difference between "
             "the two stacks is a finding in itself.")
    parser.add_argument("--serial",
                        help="match a device whose serial ends with this")
    parser.add_argument("--json", help="write the result here")
    args = parser.parse_args()

    # No --port here, deliberately. A UART build has no bulk-IN endpoint to
    # stop polling, so the condition this measures cannot exist on one, and
    # tx_drops/tx_timeout are structurally zero there (see ant_health.py).
    dev = open_device(True, serial=args.serial)
    reader = FrameReader(dev)

    if not reset_stack(dev, reader):
        sys.exit("No startup message after reset - is this the ANT firmware?")

    print("\nBaseline counters")
    before = read_health(dev, reader, "baseline")
    if before is None:
        sys.exit(
            "no 0xF6 reply. This needs CONFIG_ANT_DONGLE_HEALTH_COUNTERS=y "
            "(build with\n-DEXTRA_CONF_FILE=health.conf): two of the three "
            "assertions are counter reads, and\nwithout them a pass would "
            "only mean the dongle was still answering."
        )
    print(f"  tx_drops={before.get('tx_drops')} "
          f"tx_timeout={before.get('tx_timeout')}")
    if "tx_timeout" not in before:
        sys.exit(
            f"this dongle answers 0xF6 structure version {before['version']}, "
            "which has no tx_timeout\nfield. It is older than the firmware "
            "this test is for."
        )

    print("\nOpening a wildcard ANT+ receive channel (the load)")
    if not open_channel(dev, reader):
        return 2

    print(f"\nReading normally for {args.read_seconds:.0f} s")
    before_packets = read_for(reader, args.read_seconds)
    rate = before_packets / args.read_seconds if args.read_seconds else 0.0
    print(f"  {before_packets} packets ({rate:.1f}/s)")
    if before_packets == 0:
        sys.exit(
            "nothing is transmitting. The dongle has to be PRODUCING for the "
            "stall to mean\nanything - with an idle radio, not reading is "
            "indistinguishable from having\nnothing to read. Put an ANT+ "
            "master on the air (apps/sim on the L15, or any\nsensor) and run "
            "this again."
        )

    print(f"\nNOT READING for {args.stall_seconds:.0f} s "
          "(device stays configured)")
    # Just sleeping is the whole mechanism: with no transfer submitted, the
    # host controller issues no IN token, the dongle's endpoint stays full and
    # its bulk-IN transfer never completes. The device is never told any of
    # this - which is exactly the case a suspend/reset/unplug does NOT cover.
    time.sleep(args.stall_seconds)

    print("\nResuming")
    dev.write(EP_OUT, CAPABILITIES_REQUEST)
    round_trip = await_capabilities(reader, args.resume_timeout)
    if round_trip is None:
        print(f"  no reply within {args.resume_timeout:.1f} s")
    else:
        print(f"  capabilities reply in {round_trip * 1000:.1f} ms")

    after_packets = read_for(reader, args.after_seconds)
    print(f"  {after_packets} packets in the {args.after_seconds:.0f} s after")

    after = read_health(dev, reader, "after")
    if after is None:
        # Not "the feature is absent" - the baseline read proved it is there.
        # A dongle that answered 0xF6 before the stall and not after it is the
        # signature of the unfixed firmware: the bridge thread is parked in
        # usb_ant_write() holding tx_mutex, which is the bug itself.
        print("  no 0xF6 reply after the stall - the bridge is not answering")

    results = {
        "packets_before": before_packets,
        "packets_after": after_packets,
        "round_trip_s": round_trip,
        "counters_before": before,
        "counters_after": after,
    }

    def delta(field: str) -> int | None:
        if after is None or field not in after or field not in before:
            return None
        return after[field] - before[field]

    tx_timeout_delta = delta("tx_timeout")
    tx_drops_delta = delta("tx_drops")
    results["tx_timeout_delta"] = tx_timeout_delta
    results["tx_drops_delta"] = tx_drops_delta

    checks = [
        ("request round-trips after the stall",
         round_trip is not None and round_trip < args.resume_timeout,
         f"{round_trip * 1000:.1f} ms" if round_trip is not None
         else f"no reply in {args.resume_timeout:.1f} s"),
        ("tx_timeout climbed (the firmware abandoned a wait)",
         bool(tx_timeout_delta), f"+{tx_timeout_delta}"
         if tx_timeout_delta is not None else "unreadable"),
        ("tx_drops climbed (events were produced with nowhere to go)",
         bool(tx_drops_delta), f"+{tx_drops_delta}"
         if tx_drops_delta is not None else "unreadable"),
        ("event flow resumed",
         after_packets > 0, f"{after_packets} packets"),
    ]

    print("\nClosing")
    command(dev, reader, MESG_CLOSE_CHANNEL_ID, bytes([CHANNEL]),
            "close channel", timeout=3.0)
    close_device(dev)

    print()
    passed = True
    for name, ok, detail in checks:
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}: {detail}")
        passed = passed and ok

    results["passed"] = passed
    results["negative_control"] = args.negative_control

    if args.json:
        with open(args.json, "w") as handle:
            json.dump(results, handle, indent=2)
        print(f"\nwrote {args.json}")

    if args.negative_control:
        print()
        if passed:
            print("NEGATIVE CONTROL FAILED: every check passed on a build "
                  "that is supposed to\nlack the fix. The stall did not "
                  "reproduce, so a pass on the fixed image\nproves nothing. "
                  "Check that this really is the pre-fix image and that the "
                  "host\nstack is not reading bulk-IN behind this script's "
                  "back.")
            return 1
        print("negative control as expected: the unfixed image does not "
              "survive the stall.")
        return 0

    return 0 if passed else 1


if __name__ == "__main__":
    sys.exit(main())
